{{- $svc := .Values.api }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "daddy-config.fullname" . }}-api
  labels:
    {{- include "daddy-config.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not $svc.autoscaling.enabled }}
  replicas: {{ $svc.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "daddy-config.selectorLabels" (merge (dict "component" "api") .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "daddy-config.selectorLabels" (merge (dict "component" "api") .) | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: {{ include "daddy-config.image" (dict "global" .Values.global "image" $svc.image) }}
          imagePullPolicy: {{ $svc.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $svc.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "daddy-config.fullname" . }}-api
            - secretRef:
                name: {{ include "daddy-config.fullname" . }}-api
          livenessProbe:
            {{- toYaml $svc.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $svc.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml $svc.resources | nindent 12 }}
