{{- range list "api" "backend" "frontend" }}
{{- $svc := index $.Values . }}
{{- if $svc.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swiftremit.fullname" $ }}-{{ . }}
  labels:
    {{- include "swiftremit.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ . }}
type: Opaque
stringData:
  {{- range $k, $v := $svc.secret }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
{{- end }}
