{{- range list "api" "backend" "frontend" }}
{{- $svc := index $.Values . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "daddy-config.fullname" $ }}-{{ . }}
  labels:
    {{- include "daddy-config.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ . }}
spec:
  type: {{ $svc.service.type }}
  ports:
    - port: {{ $svc.service.port }}
      targetPort: {{ $svc.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "daddy-config.selectorLabels" (merge (dict "component" .) $) | nindent 4 }}
{{- end }}
